// Generated by tools/generate_t6c_fuselage_seed.py
#include "trainer_aircraft/config/T6CFuselageSeed.hpp"

namespace trainer_aircraft {
fuselage::DatcomFuselageConfig makeT6CFuselageDatcomSeed() {
    fuselage::DatcomFuselageConfig c;
    c.referenceAreaM2 = 16.280000000000001;
    c.referenceChordM = 1.6499999999999999;
    c.bodyLengthM = 9.75;
    c.wettedAreaM2 = 26.830128969702262;
    c.formFactor = 1.1857643878561757;
    c.baseDragCoefficient = 0;
    c.normalForceSlopePerRad = 0.13010496873096083;
    c.pitchingMomentZero = 0;
    c.pitchingMomentSlopePerRad = 0.22293111991733996;
    return c;
}
std::unique_ptr<fuselage::DatcomFuselageComponent> makeT6CFuselageWithDatcomSeed() {
    return std::make_unique<fuselage::DatcomFuselageComponent>(makeT6CFuselageDatcomSeed());
}
} // namespace trainer_aircraft
