// Generated by tools/generate_t6c_tail_seed.py
#include "trainer_aircraft/config/T6CTailSeed.hpp"

namespace trainer_aircraft {
HorizontalStabilizerConfig makeT6CHorizontalTailSeed() {
    HorizontalStabilizerConfig c;
    c.Area = 3.5724000000000005;
    c.TailSpan = 3.6640000000000001;
    c.TailMAC = 1.0109999999999999;
    c.TailAR = 3.7579487179487177;
    c.IncidenceAngle = -0.034906585039886591;
    c.MomentArm = 5.3448000000000011;
    c.ElevatorArea = 1.2860640000000001;
    c.LiftCurveSlope = 3.7349731996762969;
    c.ZeroLiftAngle = 0;
    c.ZeroLiftDragCoefficient = 0.0079343340502312041;
    c.InducedDragFactor = 0.099650699662598236;
    c.ElevatorEffectiveness = 0.60795656711449997;
    c.PitchMomentCoefficient = 0;
    c.PitchMomentCurveSlope = 0;
    c.ElevatorPitchMomentEffectiveness = -0.56767537118496536;
    c.PositionWrtCG[0] = -5.3448000000000011;
    c.PositionWrtCG[1] = 0;
    c.PositionWrtCG[2] = -0.64500000000000002;
    c.ElevatorMechanicalLimit[0] = -0.43633231299858238;
    c.ElevatorMechanicalLimit[1] = 0.3490658503988659;
    return c;
}
WingTailFlowConfig makeT6CWingTailFlowSeed() {
    WingTailFlowConfig c;
    c.referenceBodyAlphaRad = 0.021455209087647465;
    c.referenceDownwashRad = 0.02848659342042803;
    c.downwashGradientPerRad = 0.38038370461129772;
    c.referenceFlapRad = 0;
    c.flapDownwashGradientPerRad = 0.088815362266096987;
    c.dynamicPressureRatio = 0.94999999999999996;
    return c;
}
std::unique_ptr<HorizontalStabilizer> makeT6CHorizontalTailWithDownwash() {
    return std::make_unique<HorizontalStabilizer>(makeT6CHorizontalTailSeed(),
        std::make_shared<WingTailFlowField>(makeT6CWingTailFlowSeed()));
}
} // namespace trainer_aircraft
