// Generated by tools/generate_t6c_wing_seed.py; edit the generator.
#include "trainer_aircraft/config/T6CWingSeed.hpp"

namespace trainer_aircraft
{
MainWingConfig makeT6CWingCalibrationSeed()
{
    MainWingConfig c;
    c.model.derivative_axes = "body";
    c.wing.area_m2 = 16.280000000000001;
    c.wing.aspect_ratio = 6.2957847665847666;
    c.wing.mean_chord_m = 1.6499999999999999;
    c.wing.taper = 0.60638297872340419;
    c.wing.sweep_le_deg = 3.4683836797883583;
    c.wing.quarter_chord_sweep_deg = 0.99207983502819908;
    c.wing.flapped_area_m2 = 8.3223047458483279;
    c.wing.incidence_deg = 0.5;
    c.flight.rho_kg_m3 = 1.1068100000000001;
    c.flight.speed_m_s = 87.953000000000003;
    c.flight.alpha_deg = 1.2292929292929293;
    c.controls.aileron_limit_deg = 15.5;
    c.reference.aero_h = 0.25;
    c.reference.output_h = 0.29999999999999999;
    c.reference.aero_z_m = 0;
    c.reference.output_z_m = 0;
    c.reference.stability_angle_deg = 0;
    c.aero.cl_alpha_per_rad = 6.1711379272023841;
    c.aero.CL_alpha_per_rad = 4.5379476820878599;
    c.aero.CL0 = 0.20287913876294228;
    c.aero.CD0 = 0.0064965145450877511;
    c.aero.oswald_e = 0.81999999999999995;
    c.aero.Cm0 = -0.062220325741653273;
    c.aero.Cm_alpha_per_rad = 0;
    c.aero.CL_q = 1.815179072835144;
    c.aero.Cm_q = -2.1661407270665958;
    c.flap.eta_in = 0.088897668905570923;
    c.flap.eta_out = 0.55314105096799682;
    c.flap.chord_ratio = 0.25;
    c.flap.thickness_ratio = 0.12;
    c.flap.section_effectiveness_per_rad = 2.8186569781381019;
    c.flap.effectiveness_ratio_actual = 1;
    c.flap.effectiveness_ratio_reference = 1;
    c.flap.induced_factor_K = 0.31622776601683794;
    c.flap.interference_factor = 0;
    c.tabulated_flap.enabled = true;
    c.tabulated_flap.extra_induced_factor = 0.10000000000000001;
    c.lateral.CY_beta = -0.046053146303509894;
    c.lateral.CY_p = -0.22942856311890797;
    c.lateral.CY_r = 0;
    c.lateral.CY_da = 0;
    c.lateral.Cl_beta = -0.11471428155945398;
    c.lateral.Cl_p = -0.65662479693348241;
    c.lateral.Cl_r = 0.098348080599978877;
    c.lateral.Cl_da = 0.31693705795663146;
    c.lateral.Cn_beta = 0;
    c.lateral.Cn_p = -0.056640469879796922;
    c.lateral.Cn_r = -0.0039408189388575278;
    c.lateral.Cn_da = -0.01615631749648563;
    c.tabulated_flap.delta_CL = {{0, 10, 20, 23, 30, 40, 50, 60}, {0, 0.17622565488583208, 0.30884908588238613, 0.33723683956715134, 0.38408155552040329, 0.41321877697367532, 0.413789521140766, 0.39944481774121943}, "T6C split flap seed delta_CL"};
    c.tabulated_flap.delta_CD_profile = {{0, 10, 20, 23, 30, 40, 50, 60}, {0, 0.0046243524715274204, 0.017939644729869628, 0.023413508224516114, 0.03833985601588602, 0.063364419773429825, 0.089995004290114256, 0.11501956804765806}, "T6C split flap seed delta_CD_profile"};
    c.tabulated_flap.delta_Cm_at_aero_reference = {{0, 10, 20, 23, 30, 40, 50, 60}, {-0, -0.04747933909969624, -0.083211212855137745, -0.090859541836243313, -0.10348061085831232, -0.11133086409583948, -0.11148463600757406, -0.10761983529264482}, "T6C split flap seed delta_Cm"};
    return c;
}
} // namespace trainer_aircraft
